### ISSUE TITLE
DynamicPropertyFactory.getInstance().getLongProperty无法获取动态更新

### ISSUE THREAD

**Issue by aopha** [apache/servicecomb-java-chassis#1153]
CSE封装了archaius用于动态更新。

当动态本地配置文件后，使用如下代码并不能获取更新值。
DynamicLongProperty dynamicLongProperty = DynamicPropertyFactory.getInstance().getLongProperty("number",1000);
请问要如何做才能获得更新后的值。不太想自己写代码去盯着配置文件。

**Comment by wujimin** [comment]
currently, only support refresh from config center
not monitor local files, because set the scheduler as: org.apache.servicecomb.config.archaius.scheduler.NeverStartPollingScheduler

normally, it's difficult to change local files in so many nodes, but easy change in config center

so your scenes is for local testing?

**Comment by aopha** [comment]
Thanks.
Because I use different config center, it auto modify local file.
Maybe I could do it by myself like this
"public class LocalConfigurationSourceImpl implements ConfigCenterConfigurationSource"

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
