### ISSUE TITLE
消费方调用提供方的rpc接口时，接口参数异常

### ISSUE THREAD

**Issue by HoyerIsAlexander** [apache/servicecomb-java-chassis#1198]
Version：1.1.0.B036
提供方方法为sayHi（String name， String content）
1.如果传的字段为null，即调用方法为sayHi（null，null）在提供方反序列化请求的时候会报空指针异常
2.String类型的参数，如果传的是空字符串，即调用方法为sayHi（“”，“”），会报 no String-argument constructor/factory method to deserialize from String value (' ') 异常

所以内部rpc调用针对这种情况，只能new 一个对象？或者还有其他方法，当前源码中一些方法无法自定义

**Comment by wujimin** [comment]
1. already fixed in https://github.com/apache/servicecomb-java-chassis/pull/1189/commits/8cd94b6263e41257487c6343cc3d5160897e0325
  you can try by upgrade to 1.3.0-SNAPSHOT, you wait some days for 1.2.1

2. for empty but not null string, i can not reproduce the problem, can you provide a reproduce project?

**Comment by HoyerIsAlexander** [comment]
Thanks for your reply.

We use HUAWEI CSE Service actually. So The first one fixed in which version of CSE. Can we use now?

The second one i need sometime to provide a reproduce project. Maybe tomorrow

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
