### ISSUE TITLE
Customer无法获取Provider的服务地址

### ISSUE THREAD

**Issue by solomoni0999** [apache/servicecomb-java-chassis#1214]
消费者无法获取生产者地址，消费者和生产者都成功注册到服务中心，且都已经配置env模式

Caused by: org.apache.servicecomb.core.exception.CseException: No available address found. microserviceName=agentmanager, version=0.0.0+, discoveryGroupName=0.0.0+/0.0.1+/instancesNoMatch/
        at org.apache.servicecomb.core.exception.ExceptionUtils.createCseException(ExceptionUtils.java:57) ~[java-chassis-core-1.1.0.jar:1.1.0]
        at org.apache.servicecomb.core.exception.ExceptionUtils.lbAddressNotFound(ExceptionUtils.java:88) ~[java-chassis-core-1.1.0.jar:1.1.0]
        ... 91 common frames omitted

**Comment by yhs0092** [comment]
Please follow the check steps below:
1. check the log of consumer, whether there is content like `find instances[{}] from service center success. service={}/{}/{}`. If yes, then go to step 2, otherwise the provider service instance may fail to register into service center, in which case you need to check the boot up process of provider service.
2. check whether there is content like `not deployed transport {}, ignore {}.` in the log of consumer. If such log content appears, there are two possible causes. The first one is the transport components are not loaded, the second one is the transport components are loaded, but not added into `org.apache.servicecomb.core.transport.TransportManager`. It's easy to check the cause by looking up the log printed in `org.apache.servicecomb.core.transport.TransportManager#chooseOneTransport`. If in this method a transport component is chosen for the corresponding transport way, then it's quite certain that the transport component is loaded but not added into `TransportManager`. Such problem (not added to `TransportManager`) is usually caused by the repeatedly loading of Spring `ApplicationContext`, in which case you need to check the relative code and configuration : )

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
