### ISSUE TITLE
ServiceComb Java-Chassis 1.2.1版本RestServletInitializer的onStartup方法需要增加factory的对象null判断

### ISSUE THREAD

**Issue by solomoni0999** [apache/servicecomb-java-chassis#1359]
三个版本同时使用出现版本不兼容情况，导致无法启动容器，请问一下1.2.1的配套关系

**Comment by liubao68** [comment]
你可以提供下详细的错误日志吗？ 通常都是由于jar包不匹配导致的问题。 建议按照这个[项目](https://github.com/apache/servicecomb-samples/tree/master/dependency_management)配置你的pom， 或者参考[指导](http://servicecomb.apache.org/cn/docs/maven_dependency_management/)检查下冲突。

**Comment by solomoni0999** [comment]
@liubao68 我们把服务打成war包形式 丢到外部的tomcat启动，不是使用内置的tomcat方式，给的参考实例是基于内置tomcat的吧，请问外部tomcat依赖是什么，现在都没有出现springboot的启动图标在日志里

**Comment by solomoni0999** [comment]
@liubao68 @jbonofre @WillemJiang  check it，tks

**Comment by liubao68** [comment]
Do you find the cause that is because some error throws? I am not using spring boot in external tomcat, and just searched some explain on web. Seams a bit complicated. 

This is [what I got](https://dzone.com/articles/spring-boot-with-external-tomcat). 

Running serviceomb in servlet context, you need refer to [service comb servlet transport](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet.html)

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
