### ISSUE TITLE
cse service node stop but the edge still forward the request to the stopped node

### ISSUE THREAD

**Issue by leland17** [apache/servicecomb-java-chassis#1473]
In the production environment, I found when I rolling upgrade my service node, the edeg service will forword the request to the stopped node, so in this case the request failed.

or on the begin，the new started service node registed service center, when the edeg forward request to it, the request failed too.

what should I do to avoid this in my upgrade process？

**Comment by yhs0092** [comment]
When an instance is stopped, EdgeService may forward requests to this instance in a short period because the consumer side cannot get it's cached provider instance list refreshed without any latency. This is determined by the current service discovery mechanism. There are some approaches to shorten the latency. As for those requests forwarded to the down instances, some network related exceptions may occur and the instance isolation and retry mechanism in the [LB module](https://docs.servicecomb.io/java-chassis/zh_CN/references-handlers/loadbalance.html) may cover them and make the business invoke still success outside of the consumer side. Be careful the retry mechanism is limited and they cannot ensure the business invocation success in all of the cases. You can get some references in #1238.

As for the instance start up cases, in terms of the Java-Chassis, when the instances get registered onto the service center, they are ready to process the requests. Maybe the failures occur because some of your business related modules are not ready at this time. I guess you can implement the `org.apache.servicecomb.core.BootListener` and get you modules initiated in the proper stage. The enum `org.apache.servicecomb.core.BootListener.EventType` lists the stages in the microservice instance lifecycle, you can find their meaning in Java -Chassis source code.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
